# Site settings
title: CSSU
email: cssu@cdf.toronto.edu
url: https://cssu.ca
description: "University of Toronto Computer Science Student Union"
twitter_username:  cssu
github_username:   cssu
facebook_username: UofTCSSU

# Build settings
exclude: ['README.md', 'vendor']
markdown: redcarpet
permalink: pretty

# redcarpet settings
redcarpet:
  extensions: []

# Site nav
navigation:
 - title: Events
   url: /events/
 - title: News
   url: /news/
 - title: Store
   url: /store/
 - title: Sponsors
   url: /sponsors/
 - title: Volunteer
   url: /volunteer/
 - title: Wiki
   url: /w/
 - title: About
   url: /about/

# Enable asset processing
assets:
  js_compressor:  uglifier
  css_compressor: sass

# Disable asset concatenation
debug: true
