# Site settings
title: CSSU
email: contact@cssu.io
description: "University of Toronto Computer Science Student Union"
twitter_username: cssu
github_username:  cssu

# Build settings
exclude: ['README.md']
markdown: kramdown
permalink: /:categories/:title

# kramdown settings
kramdown:
  input: GFM
  use_coderay: true
  coderay:
    coderay_line_numbers: nil
