# Site settings
title: CSSU
email: cssu@cdf.toronto.edu
description: "University of Toronto Computer Science Student Union"
twitter_username:  cssu
github_username:   cssu
facebook_username: UofTCSSU

# Build settings
exclude: ['README.md']
markdown: kramdown
permalink: /:categories/:title

# kramdown settings
kramdown:
  input: GFM
  use_coderay: true
  coderay:
    coderay_line_numbers: nil

# Site nav
navigation:
 - title: Events
   url: /events/
 - title: News
   url: /news/
 - title: Store
   url: /store/
 - title: About
   url: /about/
 - title: Members
   url: /members/
 - title: Sponsers
   url: /sponsers/
 - title: Wiki
   url: /w/

# Sass
sass:
  sass_dir: css
  style: :compressed
